name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t jeancbezerra/demo-swagger-api:latest .

      - name: Push da imagem para o Docker Hub
        run: |
          docker push jeancbezerra/demo-swagger-api:latest
